version: '3.9'
services:
  controller:
    build: ./server
    privileged: true
    restart: unless-stopped
    environment:
     - ADMIN_USER=${ADMIN_USER}
     - ADMIN_PASSWORD=${ADMIN_PASSWORD}
     - LOG_LEVEL=${LOG_LEVEL}
     - DB_FILE_PATH=/app/db/db.sqlite
    volumes:
     - controller-db:/app/db
    
volumes:
  controller-db: